"""Self-contained, accessible static research dashboard with local-only filters."""
import json


def render_dashboard(data: dict) -> str:
    payload = json.dumps(data, ensure_ascii=True, allow_nan=False).replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")
    return TEMPLATE.replace("__EVIDENCE_PAYLOAD__", payload)


TEMPLATE = r'''<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>EvoNN · Research evidence</title>
<style>
:root{--paper:#f5f3eb;--ink:#182d31;--muted:#53686b;--line:#cbd3ce;--accent:#ba431d;--light:#fffdf7;--good:#21624b;--bad:#9a3425}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.55 system-ui,sans-serif}a{color:var(--ink)}header{padding:44px 5vw 30px;border-bottom:1px solid var(--ink)}.eyebrow{font:12px ui-monospace,monospace;text-transform:uppercase;letter-spacing:.16em;color:var(--accent)}h1{font:clamp(32px,5vw,66px)/1.05 Georgia,serif;letter-spacing:-.04em;margin:17px 0}h2{font:27px/1.2 Georgia,serif;margin:0 0 10px}h3{font-size:16px;margin:28px 0 9px}p{max-width:85ch;color:var(--muted)}nav{display:flex;flex-wrap:wrap;gap:18px;font:13px ui-monospace,monospace}.filters{position:sticky;top:0;z-index:2;background:var(--light);border-bottom:1px solid var(--line);padding:15px 5vw;display:flex;gap:14px;flex-wrap:wrap}.filters label{font-size:11px;text-transform:uppercase;letter-spacing:.06em;display:grid;gap:4px}select{font:13px system-ui;border:1px solid var(--line);border-radius:0;background:white;color:var(--ink);padding:7px;max-width:210px}select:focus,a:focus{outline:3px solid #d87340;outline-offset:3px}main{padding:0 5vw 60px}section{padding:34px 0;border-bottom:1px solid var(--line);scroll-margin-top:125px}.numbers{display:grid;grid-template-columns:repeat(4,1fr);gap:20px}.number{font:42px Georgia,serif;display:block}.caption{font:12px ui-monospace,monospace;color:var(--muted)}.table-scroll{overflow:auto;max-height:510px;background:var(--light);border:1px solid var(--line)}table{border-collapse:collapse;min-width:100%;font-size:12px}th,td{padding:10px 12px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top;white-space:nowrap}th{position:sticky;top:0;background:#e6eae1;font:11px ui-monospace,monospace;text-transform:uppercase}td{font-variant-numeric:tabular-nums}td:last-child{white-space:normal;min-width:120px}.empty{padding:18px;border-left:3px solid var(--accent);background:var(--light);color:var(--muted)}.note{font-size:13px;color:var(--muted)}.plot{background:var(--light);border:1px solid var(--line);width:100%;height:350px;display:block}.grid{display:grid;grid-template-columns:1fr 1fr;gap:25px}.status{color:var(--accent);font-weight:600}footer{padding:25px 5vw;font:12px ui-monospace,monospace;color:var(--muted)}@media(max-width:850px){.grid{grid-template-columns:1fr}.numbers{grid-template-columns:1fr 1fr}.filters{position:static}header{padding-top:25px}section{scroll-margin-top:10px}}
</style>
<header><div class="eyebrow">EvoNN Research / Evidence notebook</div><h1>What the runs actually show.</h1><p>Compare the same pack, budget and seed. Follow the measurements back to their run IDs. Missing systems, failed fits and absent floors remain visible.</p><nav><a href="#health">Lane health</a><a href="#winners">Winners</a><a href="#aggregate">Aggregate evidence</a><a href="#explorer">Evidence Explorer</a><a href="#runtime">Runtime</a><a href="#history">Run history</a></nav></header>
<div class="filters" aria-label="Evidence filters"><label>Cohort<select id="cohort"></select></label><label>Backend<select id="backend"></select></label><label>Hardware<select id="device"></select></label><label>Benchmark<select id="benchmark"></select></label><label>Task kind<select id="task_kind"></select></label><label>Evidence x-axis<select id="axis"><option value="budget">Evaluation budget</option><option value="case">Run case</option></select></label></div>
<main><section aria-label="Evidence overview"><div class="numbers" id="overview"></div><p id="scope" class="note"></p></section>
<section id="health"><div class="eyebrow">01 / Trust before ranking</div><h2>Lane health by budget</h2><div id="health-table"></div><h3>Measurement downgrade reasons</h3><div id="quality-table"></div></section>
<section id="winners"><div class="eyebrow">02 / Same-case outcomes</div><h2>Benchmark winners · All systems</h2><p class="note">A sole participating system has a best result, but no comparative win. Ceiling ties never count as superiority.</p><div id="winners-all"></div><h3>Benchmark winners · Projects only</h3><div id="winners-projects"></div><h3>Ceiling ties · Separate evidence category</h3><div id="ceiling-table"></div></section>
<section id="decisions"><h2>Registry decision evidence</h2><p class="note">L4 describes evidence quality. Best observed, likely gain and a promotion decision remain distinct. Raw artifact availability is checked separately.</p><div id="decision-table"></div><h3>Required diagnostics</h3><div id="diagnostics-table"></div></section>
<section id="aggregate"><div class="eyebrow">03 / Breadth and repeatability</div><h2>Overall Leaderboard: All Systems</h2><div id="leader-all"></div><h3>Overall Leaderboard: Projects Only</h3><div id="leader-projects"></div><h3>Aggregate Evidence: All Systems</h3><div id="spread-all"></div><h3>Aggregate Evidence: Projects Only</h3><div id="spread-projects"></div><p class="note">Intervals are descriptive normal approximations over independent seed means (n ≥ 3), grouped by benchmark, budget, cohort, backend version, host and training protocol. Repeated identical seeds do not increase n. No significance claim is made.</p><h3>Pairwise seed deltas</h3><div id="pairwise"></div><h3>Per-Seed Aggregate Snapshots: All Systems</h3><div id="seed-all"></div><h3>Per-Seed Aggregate Snapshots: Projects Only</h3><div id="seed-projects"></div><h3>Engine Rank By Benchmark Family: All Systems</h3><div id="family-all"></div><h3>Engine Rank By Benchmark Family: Projects Only</h3><div id="family-projects"></div></section>
<section id="explorer"><div class="eyebrow">04 / Inspect the measurements</div><h2>Benchmark Trend View</h2><h3>Evidence Explorer</h3><p class="note">Points show the best successful outcome per system, benchmark and run. For each benchmark, observed scores are mapped to [0, 1] in the better direction across the filtered evidence; 1 is best observed, not a scientific ceiling. Equal observed values map to 0.5. Raw values remain in the table and point descriptions.</p><svg class="plot" id="plot" role="img" aria-label="Normalized engine scores over budget or case"></svg><p id="plot-description" class="note"></p><div id="raw-table"></div></section>
<section id="runtime"><div class="eyebrow">05 / Cost of the evidence</div><h2>Runtime and performance</h2><div id="runtime-table"></div><h3>Family runtime allocation</h3><div id="allocation-table"></div><p class="note">Raw score/second is metric/time, not a utility rate for lower-is-better metrics. Worker peak memory includes the interpreter and imports. No missing measurement is estimated.</p><h3>Transfer provenance</h3><div id="transfer-table"></div></section>
<section id="history"><div class="eyebrow">06 / Longitudinal record</div><h2>Recent full-run budget overview</h2><p class="note">Last 20 comparison cases. Rebuilding this page never reruns a model.</p><div id="history-table"></div></section>
</main><footer>Local static artifact · <a href="fair_matrix_dashboard.json">Complete JSON evidence</a> · <a href="trends/fair_matrix_trends.md">Default trend report</a></footer>
<script type="application/json" id="data">__EVIDENCE_PAYLOAD__</script>
<script>
'use strict';const D=JSON.parse(document.getElementById('data').textContent);const $=id=>document.getElementById(id);const fields=['cohort','backend','device','benchmark','task_kind'];const colors={contenders:'#ba431d',prism:'#21624b',topograph:'#345a99',stratograph:'#79569b',primordia:'#94701f'};
function fmt(x){if(x===null||x===undefined)return 'unavailable';if(typeof x==='number')return Number.isInteger(x)?String(x):Number(x.toPrecision(6)).toString();if(typeof x==='object')return JSON.stringify(x);return String(x)}
function table(id,rows,columns){const host=$(id);host.replaceChildren();if(!rows.length){const p=document.createElement('p');p.className='empty';p.textContent='No evidence for this slice. Missing participation is not a loss.';host.append(p);return}const wrap=document.createElement('div');wrap.className='table-scroll';const t=document.createElement('table'),head=document.createElement('thead'),tr=document.createElement('tr');for(const [label] of columns){const th=document.createElement('th');th.scope='col';th.textContent=label;tr.append(th)}head.append(tr);t.append(head);const body=document.createElement('tbody');for(const r of rows){const line=document.createElement('tr');for(const [,getter] of columns){const td=document.createElement('td');td.textContent=fmt(typeof getter==='function'?getter(r):r[getter]);line.append(td)}body.append(line)}t.append(body);wrap.append(t);host.append(wrap)}
for(const field of fields){const all=document.createElement('option');all.value='';all.textContent='All '+field.replace('_',' ');$(field).append(all);for(const value of [...new Set(D.rows.map(r=>r[field]))].sort()){const o=document.createElement('option');o.value=value;o.textContent=value;$(field).append(o)}$(field).addEventListener('change',draw)}$('axis').addEventListener('change',draw);
const match=r=>fields.every(f=>!$(f).value||r[f]===$(f).value);
function credits(ws){const groups={};for(const w of ws){for(const name of w.winners){const r=w.values.find(r=>r.engine===name);const context=JSON.stringify(w.values.map(v=>[v.engine,v.backend,v.host_fingerprint,v.protocol_fingerprint||'legacy']).sort((a,b)=>a[0].localeCompare(b[0])));const k=JSON.stringify([w.cohort,w.pack,w.budget,name,context]);groups[k]??={cohort:w.cohort,pack:w.pack,budget:w.budget,engine:name,backend:r.backend,protocol:r.protocol_fingerprint||'legacy',host:r.host_fingerprint,comparison_context:w.values.map(v=>v.engine+' '+v.backend+' '+(v.protocol_fingerprint||'legacy').slice(0,8)).sort().join('; '),credit:0,wins:0,ties:0,ceilings:0,sole:0};const g=groups[k];if(!w.comparison_available)g.sole++;else if(w.ceiling_tie)g.ceilings++;else if(w.case_win||w.tie&&w.values.every(r=>r.accounting_state==='complete'&&!['reference','exploratory'].includes(r.operating_state))){g.credit+=1/w.winners.length;if(w.tie)g.ties++;else g.wins++}}}return Object.values(groups).sort((a,b)=>a.cohort.localeCompare(b.cohort)||b.credit-a.credit)}
function comparisonGroups(rows){const groups=new Map(),base=rows.filter(r=>r.engine==='contenders');for(const r of rows.filter(r=>r.engine!=='contenders')){const key=r.comparison_fingerprint||('unavailable:'+r.run_id);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r)}if(groups.size===1)[...groups.values()][0].push(...base);else if(base.length)groups.set('baseline',base);return [...groups.values()]}
function selectedWinners(best,projectsOnly){const groups=new Map();for(const row of best){if(projectsOnly&&row.engine==='contenders')continue;const key=JSON.stringify([row.cohort,row.case_id,row.benchmark]);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row)}return [...groups.values()].flatMap(comparisonGroups).map(values=>{const first=values[0],ok=values.filter(r=>r.status==='ok'&&r.accounting_state==='complete'&&!['reference','exploratory'].includes(r.operating_state));const value=ok.length?(first.direction==='max'?Math.max:Math.min)(...ok.map(r=>r.value)):null;const chosen=ok.filter(r=>r.value===value),names=chosen.map(r=>r.engine),tie=chosen.length>1;const trusted=ok.every(r=>r.accounting_state==='complete'&&!['reference','exploratory'].includes(r.operating_state));const c=D.cases.find(c=>c.comparison_id===first.case_id);const missing=values.filter(r=>r.status!=='ok').map(r=>({engine:r.engine,status:r.status,reason:r.reason}));for(const f of c?.failures||[]){if(!projectsOnly||f.system!=='contenders')missing.push({engine:f.system,status:'missing_export',reason:f.reason})}return {cohort:first.cohort,case_id:first.case_id,benchmark:first.benchmark,pack:first.pack,budget:first.budget,value,winners:names,tie,ceiling_tie:tie&&first.ceiling!==null&&value===first.ceiling,backend_classes:[...new Set(values.map(r=>r.backend))].sort(),portability_only:values.some(r=>r.backend==='numpy_fallback'),comparison_available:ok.length>=2,case_win:ok.length>=2&&!tie&&trusted,failures_or_missing:missing,values}})}
function selectedPairs(best){const groups=new Map();for(const r of best){if(r.status!=='ok'||r.accounting_state!=='complete'||['reference','exploratory'].includes(r.operating_state))continue;const key=JSON.stringify([r.cohort,r.case_id,r.benchmark,r.seed]);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r)}return [...groups.values()].flatMap(comparisonGroups).flatMap(rows=>rows.flatMap(a=>rows.filter(b=>a.engine<b.engine&&(a.engine==='contenders'||b.engine==='contenders'||a.comparison_fingerprint&&a.comparison_fingerprint===b.comparison_fingerprint)&&JSON.stringify(a.seeding)===JSON.stringify(b.seeding)).map(b=>({case_id:a.case_id,benchmark:a.benchmark,seed:a.seed,left:a.engine,right:b.engine,raw_delta:a.value-b.value,advantage_left:(a.value-b.value)*(a.direction==='max'?1:-1)}))))}
function draw(){
const analysis=D.analysis;table('decision-table',analysis?.groups||[],[['Pack','pack'],['Engine','engine'],['Budget','budget'],['Independent seeds','n'],['Statistical label','statistical_label'],['Aggregate','aggregation_label'],['Level','level'],['Effect','effect_mean'],['95% bootstrap interval','bootstrap_ci95'],['Primary decision',()=>analysis.decision_category],['Blockers','blockers']]);
const diagnostics=analysis?.diagnostics||D.descriptive_evidence?.diagnostics;table('diagnostics-table',diagnostics?Object.entries(diagnostics).map(([name,value])=>({name,value})):[],[['Diagnostic','name'],['Evidence','value']]);
const rows=D.rows.filter(match), best=D.statistics.per_seed.filter(match), ids=new Set(rows.map(r=>r.case_id));const cases=D.cases.filter(c=>ids.has(c.comparison_id)||fields.every(f=>!$(f).value));const bench=new Set(rows.map(r=>r.benchmark));const all=selectedWinners(best,false);const projects=selectedWinners(best,true);$('overview').replaceChildren();for(const [value,label] of [[cases.length,'Comparison cases'],[new Set(rows.map(r=>r.run_id)).size,'Verified runs'],[new Set(rows.map(r=>r.seed)).size,'Distinct seed IDs'],[rows.filter(r=>r.status==='failed').length,'Failed outcomes']]){const box=document.createElement('div'),n=document.createElement('span'),l=document.createElement('span');n.className='number';n.textContent=value;l.className='caption';l.textContent=label;box.append(n,l);$('overview').append(box)}$('scope').textContent='Absent systems: '+(D.absent_systems.join(', ')||'none')+'. Contract evidence does not establish scientific superiority.';
table('health-table',cases,[['Case','comparison_id'],['Budget',c=>c.case.budget],['Operating',c=>c.acceptance.operating_state],['Accounting',c=>c.acceptance.accounting_state],['Repeatability',c=>c.acceptance.repeatability_state],['Engine only',c=>c.acceptance.engine_only],['Blockers',c=>c.acceptance.blockers.join('; ')||'none']]);const runs=new Set(rows.map(r=>r.run_id));table('quality-table',D.output_quality.filter(q=>runs.has(q.run_id)||q.level==='L0'&&cases.some(c=>c.comparison_id===q.case_id)),[['Run','run_id'],['Level','level'],['Gaps',q=>q.gaps.join('; ')||'none'],['Next level','next_level']]);
const wc=[['Case','case_id'],['Benchmark','benchmark'],...['contenders','prism','topograph','stratograph','primordia'].map(name=>[name,w=>{const r=w.values.find(r=>r.engine===name);return r?(r.status==='ok'?r.value:r.status):'absent'}]),['Best value','value'],['Winners','winners'],['Tie','tie'],['Ceiling tie','ceiling_tie'],['Comparison','comparison_available'],['Failures / missing','failures_or_missing']];table('winners-all',all,wc);table('winners-projects',projects,wc.filter(c=>c[0]!=='contenders'));table('ceiling-table',all.filter(w=>w.ceiling_tie),wc);
const lc=[['Cohort','cohort'],['Pack','pack'],['Budget','budget'],['Engine','engine'],['Backend','backend'],['Protocol',r=>r.protocol.slice(0,12)],['Host',r=>r.host.slice(0,12)],['Compared protocols','comparison_context'],['Win credit','credit'],['Wins','wins'],['Ties','ties'],['Ceiling ties','ceilings'],['Sole participant','sole']];table('leader-all',credits(all),lc);table('leader-projects',credits(projects),lc);
const spread=D.statistics.spread.filter(r=>fields.every(f=>!$(f).value||!Object.hasOwn(r,f)||r[f]===$(f).value));const sc=[['Cohort','cohort'],['Pack','pack'],['Budget','budget'],['Benchmark','benchmark'],['Engine','engine'],['Backend','backend'],['Protocol',r=>(r.protocol_fingerprint||'legacy').slice(0,12)],['Host',r=>r.host_fingerprint.slice(0,12)],['Seeds','n'],['Mean','mean'],['Range',r=>[r.min,r.max]],['95% interval','ci95'],['Gap','gap']];table('spread-all',spread,sc);table('spread-projects',spread.filter(r=>r.engine!=='contenders'),sc);table('pairwise',selectedPairs(best),[['Case','case_id'],['Benchmark','benchmark'],['Seed','seed'],['Left','left'],['Right','right'],['Raw delta','raw_delta'],['Advantage left','advantage_left']]);
const pc=[['Case','case_id'],['Seed','seed'],['Engine','engine'],['Benchmark','benchmark'],['Budget','budget'],['Value','value'],['Status','status']];table('seed-all',best,pc);table('seed-projects',best.filter(r=>r.engine!=='contenders'),pc);
function family(ws){const grouped={};for(const w of ws){const row=best.find(r=>r.case_id===w.case_id&&r.benchmark===w.benchmark);const k=w.cohort+' / '+(row?.family||'unknown');(grouped[k]??=[]).push(w)}return Object.entries(grouped).flatMap(([family,ws])=>credits(ws).map((r,i)=>({...r,family,rank:i+1})))}const fc=[['Cohort / family','family'],['Rank','rank'],['Engine','engine'],['Credit','credit'],['Ceiling ties','ceilings']];table('family-all',family(all),fc);table('family-projects',family(projects),fc);
plot(best.filter(r=>r.status==='ok'));table('raw-table',rows.slice(0,1000),[['Case','case_id'],['Run','run_id'],['Engine','engine'],['Benchmark','benchmark'],['Outcome','outcome_id'],['Budget','budget'],['Metric','metric'],['Direction','direction'],['Raw value','value'],['Model family','model_family'],['Model backend','model_backend'],['Raw score / second','score_per_second'],['Status','status'],['Reason','reason']]);
const runtime=[...new Map(rows.map(r=>[r.run_id,r])).values()];table('runtime-table',runtime,[['Run','run_id'],['Backend','backend'],['Device','device'],['Wall seconds including pauses','wall_clock'],['Active run seconds','active_run_seconds'],['Evals / second','evals_per_second'],['Seconds / success','seconds_per_success'],['Evaluation semantics','evaluation_semantics'],['Cached','cached_evaluations'],['Failed','failed_evaluations'],['Invalid','invalid_evaluations']]);const allocation={};for(const r of rows){const key=r.run_id+' / '+(r.model_family||'model family unavailable');allocation[key]??={label:key,seconds:0,missing:0};if(r.train_seconds===null)allocation[key].missing++;else allocation[key].seconds+=r.train_seconds}table('allocation-table',Object.values(allocation),[['Run / family','label'],['Measured fit seconds','seconds'],['Outcomes without duration','missing']]);table('transfer-table',runtime.filter(r=>r.seeding.seeding_enabled),[['Run','run_id'],['Provenance','seeding']]);table('history-table',cases.slice(-20).reverse(),[['Case','comparison_id'],['Pack',c=>c.case.pack],['Budget',c=>c.case.budget],['Seed',c=>c.case.seed],['Runs',c=>c.runs.map(r=>r.run_id)],['Operating',c=>c.acceptance.operating_state]]);
}
function plot(rows){const svg=$('plot');svg.replaceChildren();const width=1000,height=350,left=60,right=25,top=25,bottom=55;svg.setAttribute('viewBox',`0 0 ${width} ${height}`);function el(tag,attrs,text){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v] of Object.entries(attrs))e.setAttribute(k,v);if(text)e.textContent=text;svg.append(e);return e}const cases=[...new Set(rows.map(r=>r.case_id))].sort();const axis=$('axis').value;const xs=rows.map(r=>axis==='budget'?r.budget:cases.indexOf(r.case_id));const min=Math.min(...xs),max=Math.max(...xs);for(let y=0;y<=1;y+=.25){const py=height-bottom-y*(height-bottom-top);el('line',{x1:left,x2:width-right,y1:py,y2:py,stroke:'#d8ddd4'});el('text',{x:12,y:py+4,fill:'#53686b','font-size':12},y.toFixed(2))}const ranges={};for(const r of rows){ranges[r.benchmark]??=[];ranges[r.benchmark].push(r.value)}for(const r of rows){const values=ranges[r.benchmark],low=Math.min(...values),high=Math.max(...values);let norm=high===low?.5:(r.value-low)/(high-low);if(r.direction==='min'&&high!==low)norm=1-norm;const x=axis==='budget'?r.budget:cases.indexOf(r.case_id);const px=left+(max===min?.5:(x-min)/(max-min))*(width-left-right),py=height-bottom-norm*(height-bottom-top);const dot=el('circle',{cx:px,cy:py,r:4.5,fill:colors[r.engine]||'#182d31',opacity:.72,tabindex:0});const title=document.createElementNS(svg.namespaceURI,'title');title.textContent=`${r.engine} · ${r.benchmark} · budget ${r.budget} · seed ${r.seed} · raw ${r.value} · ${r.case_id}`;dot.append(title)}if(rows.length){for(const x of [...new Set(xs)].sort((a,b)=>a-b).filter((_,i,a)=>a.length<=12||i%Math.ceil(a.length/12)===0)){const px=left+(max===min?.5:(x-min)/(max-min))*(width-left-right);el('text',{x:px,y:height-25,'text-anchor':'middle',fill:'#53686b','font-size':12},axis==='budget'?String(x):String(x+1))}}$('plot-description').textContent=rows.length?`${rows.length} points. ${axis==='case'?'Case numbers follow sorted case IDs in the table. ':''}Colors: Contenders orange; Prism green; Topograph blue; Stratograph purple; Primordia ochre. Raw table shows up to 1,000 outcomes; filter to narrow.`:'No successful measurements for these filters.'}
draw();
</script></html>'''
